const abyssPresets = {
    noEffect: "无特殊效果",
    normalTwo: "2只普通蝗虫",
    smallFour: "4只小型蝗虫",
    blackFear: "黑色蝗虫, 使敌人恐惧",
    blueConfuse: "蓝色蝗虫, 击退敌人并使其混乱",
    blueFreeze: "蓝色蝗虫, 冻结敌人",
    cyanDestroyProjectiles: "青色蝗虫, 阻挡敌人弹幕",
    cyanElectricity: "淡蓝色蝗虫, 带有电弧, 每个电弧造成0.1点伤害",
    grayConfuse: "灰色蝗虫, 使敌人混乱",
    grayPetrify: "灰色蝗虫, 使敌人石化",
    grayMagnetize: "灰色蝗虫, 使敌人磁化",
    graySlow: "淡灰色蝗虫, 使敌人减速",
    grayBones: "淡灰色蝗虫, 击中敌人时产生1-3个骨片",
    greenPoison: "绿色蝗虫, 使敌人中毒",
    pinkMimic: "粉色蝗虫, 触发随机特效",
    pinkCharm: "粉色蝗虫, 魅惑敌人",
    purpleHoming: "紫色跟踪蝗虫",
    orangeBurn: "橙色蝗虫, 使敌人燃烧",
    redBleed: "暗红色蝗虫, 使敌人流血",
    redLarge: "较大的红色蝗虫",
    whiteBeam: "白色蝗虫, 生成造成3x角色伤害的光束",
    whiteGodhead: "白色蝗虫, 带有伤害光环, 造成每秒60点伤害",
    yellowExplode: "黄色蝗虫, 接触敌人时有几率爆炸",
    yellowPoisonExplode: "黄色蝗虫, 使敌人中毒, 接触敌人时有几率爆炸",
    yellowMimicExplode: "黄色蝗虫, 触发随机特效, 接触敌人时有几率爆炸",
}

export const abyssSynergies = {
    6: "较快的红色蝗虫, 造成伤害更快",
    10: "2只青色蝗虫, 阻挡敌人弹幕",
    12: abyssPresets.redLarge,
    19: abyssPresets.yellowExplode,
    37: abyssPresets.yellowExplode,
    39: abyssPresets.grayPetrify,
    40: abyssPresets.yellowExplode,
    47: abyssPresets.yellowExplode,
    52: abyssPresets.yellowExplode,
    41: abyssPresets.blackFear,
    53: abyssPresets.grayMagnetize,
    58: abyssPresets.cyanDestroyProjectiles,
    62: abyssPresets.redBleed,
    63: abyssPresets.cyanElectricity,
    65: abyssPresets.yellowExplode,
    66: abyssPresets.graySlow,
    68: abyssPresets.cyanElectricity,
    69: abyssPresets.redLarge,
    71: "较小的红色蝗虫",
    73: abyssPresets.cyanDestroyProjectiles,
    77: abyssPresets.cyanDestroyProjectiles,
    89: abyssPresets.graySlow,
    95: abyssPresets.cyanElectricity,
    99: abyssPresets.graySlow,
    100: abyssPresets.purpleHoming,
    104: "1只正常红色蝗虫和2只较小的红色蝗虫",
    106: abyssPresets.yellowExplode,
    108: abyssPresets.cyanDestroyProjectiles,
    110: abyssPresets.grayPetrify,
    111: abyssPresets.greenPoison,
    112: abyssPresets.cyanDestroyProjectiles,
    114: "较大的红色蝗虫, 攻击更快",
    116: abyssPresets.cyanElectricity,
    118: "较大的黑色蝗虫",
    124: abyssPresets.pinkMimic,
    125: abyssPresets.yellowExplode,
    136: abyssPresets.yellowExplode,
    137: abyssPresets.yellowExplode,
    140: abyssPresets.yellowExplode,
    149: abyssPresets.greenPoison,
    153: abyssPresets.smallFour,
    160: abyssPresets.whiteBeam,
    162: abyssPresets.cyanDestroyProjectiles,
    164: abyssPresets.orangeBurn,
    168: abyssPresets.yellowExplode,
    169: abyssPresets.redLarge,
    171: abyssPresets.graySlow,
    172: abyssPresets.cyanDestroyProjectiles,
    178: "白色蝗虫, 使敌人石化, 生成造成3x角色伤害的光束",
    180: abyssPresets.greenPoison,
    181: abyssPresets.whiteBeam,
    182: "较慢的白色追踪蝗虫, 生成造成3x角色伤害的光束",
    187: abyssPresets.cyanDestroyProjectiles,
    190: abyssPresets.yellowExplode,
    191: abyssPresets.pinkMimic,
    192: abyssPresets.purpleHoming,
    200: abyssPresets.pinkCharm,
    201: abyssPresets.grayConfuse,
    202: abyssPresets.grayPetrify,
    207: abyssPresets.cyanDestroyProjectiles,
    209: abyssPresets.yellowPoisonExplode,
    210: abyssPresets.cyanDestroyProjectiles,
    213: abyssPresets.cyanDestroyProjectiles,
    220: abyssPresets.yellowExplode,
    224: abyssPresets.smallFour,
    228: abyssPresets.blackFear,
    230: abyssPresets.blackFear,
    231: "黑色蝗虫, 使敌人减速",
    232: abyssPresets.graySlow,
    242: abyssPresets.cyanDestroyProjectiles,
    243: abyssPresets.cyanDestroyProjectiles,
    244: abyssPresets.cyanDestroyProjectiles,
    245: abyssPresets.normalTwo,
    248: abyssPresets.redLarge,
    250: abyssPresets.yellowExplode,
    256: "黄色蝗虫, 使敌人燃烧, 接触敌人时有几率爆炸",
    258: abyssPresets.pinkMimic,
    259: abyssPresets.blackFear,
    264: abyssPresets.purpleHoming,
    265: abyssPresets.cyanDestroyProjectiles,
    266: abyssPresets.graySlow,
    267: abyssPresets.cyanElectricity,
    272: abyssPresets.yellowExplode,
    273: abyssPresets.yellowPoisonExplode,
    276: abyssPresets.blueConfuse,
    277: abyssPresets.blackFear,
    279: "大型青色缓慢蝗虫, 阻挡敌人弹幕",
    281: abyssPresets.cyanDestroyProjectiles,
    289: abyssPresets.orangeBurn,
    294: abyssPresets.blueConfuse,
    298: abyssPresets.cyanDestroyProjectiles,
    300: abyssPresets.blueConfuse,
    303: abyssPresets.cyanDestroyProjectiles,
    309: abyssPresets.blueConfuse,
    310: "较慢的大型黑色蝗虫",
    313: abyssPresets.cyanDestroyProjectiles,
    315: abyssPresets.grayMagnetize,
    317: abyssPresets.greenPoison,
    326: abyssPresets.cyanDestroyProjectiles,
    330: "小型红色快速蝗虫, 造成伤害更快",
    331: abyssPresets.whiteGodhead,
    336: "红色缓慢蝗虫",
    337: abyssPresets.graySlow,
    338: abyssPresets.grayPetrify,
    347: abyssPresets.normalTwo,
    350: abyssPresets.greenPoison,
    351: "绿色蝗虫, 击退敌人并使其中毒和混乱",
    353: abyssPresets.yellowExplode,
    356: abyssPresets.cyanElectricity,
    360: abyssPresets.normalTwo,
    363: abyssPresets.cyanDestroyProjectiles,
    366: "2只黄色蝗虫, 接触敌人时有几率爆炸",
    367: "黄色蝗虫, 使敌人减速, 接触敌人时有几率爆炸",
    371: abyssPresets.yellowExplode,
    372: abyssPresets.cyanElectricity,
    374: abyssPresets.whiteBeam,
    375: abyssPresets.cyanDestroyProjectiles,
    378: abyssPresets.yellowExplode,
    379: abyssPresets.redLarge,
    387: abyssPresets.graySlow,
    391: abyssPresets.pinkCharm,
    393: abyssPresets.greenPoison,
    395: abyssPresets.cyanElectricity,
    398: "蓝色蝗虫, 缩小敌人",
    401: abyssPresets.yellowExplode,
    402: abyssPresets.pinkMimic,
    403: abyssPresets.pinkMimic,
    404: "青色蝗虫, 使敌人中毒, 阻挡敌人弹幕",
    405: abyssPresets.pinkMimic,
    415: abyssPresets.whiteBeam,
    417: abyssPresets.whiteGodhead,
    418: abyssPresets.pinkMimic,
    421: abyssPresets.pinkCharm,
    423: abyssPresets.cyanDestroyProjectiles,
    425: abyssPresets.graySlow,
    427: abyssPresets.yellowExplode,
    432: abyssPresets.yellowMimicExplode,
    441: "较大的黑色蝗虫",
    446: abyssPresets.greenPoison,
    448: abyssPresets.redBleed,
    449: abyssPresets.cyanDestroyProjectiles,
    453: abyssPresets.grayBones,
    457: abyssPresets.cyanDestroyProjectiles,
    459: abyssPresets.greenPoison,
    460: abyssPresets.grayConfuse,
    466: abyssPresets.greenPoison,
    473: "较大较慢的红色蝗虫",
    478: abyssPresets.grayPetrify,
    483: "较大的黄色蝗虫, 接触敌人时有几率爆炸",
    488: abyssPresets.pinkMimic,
    495: abyssPresets.orangeBurn,
    497: abyssPresets.grayConfuse,
    502: abyssPresets.graySlow,
    506: abyssPresets.redBleed,
    508: abyssPresets.redBleed,
    510: abyssPresets.pinkMimic,
    512: abyssPresets.grayMagnetize,
    514: "灰色蝗虫, 使敌人石化和混乱",
    517: abyssPresets.yellowExplode,
    519: abyssPresets.pinkMimic,
    520: abyssPresets.cyanElectricity,
    524: abyssPresets.cyanElectricity,
    525: abyssPresets.cyanDestroyProjectiles,
    533: abyssPresets.whiteBeam,
    541: abyssPresets.grayBones,
    542: abyssPresets.grayBones,
    544: abyssPresets.grayBones,
    545: abyssPresets.grayBones,
    546: abyssPresets.grayPetrify,
    548: abyssPresets.grayBones,
    549: abyssPresets.grayBones,
    553: abyssPresets.greenPoison,
    554: abyssPresets.blackFear,
    561: "小型红色快速蝗虫, 造成伤害更快",
    563: abyssPresets.yellowMimicExplode,
    568: abyssPresets.cyanDestroyProjectiles,
    570: abyssPresets.pinkMimic,
    574: abyssPresets.whiteGodhead,
    575: abyssPresets.graySlow,
    577: "2只青色蝗虫, 阻挡敌人弹幕",
    581: abyssPresets.cyanDestroyProjectiles,
    583: abyssPresets.yellowExplode,
    591: abyssPresets.pinkCharm,
    594: abyssPresets.greenPoison,
    596: abyssPresets.blueFreeze,
    603: abyssPresets.cyanElectricity,
    606: abyssPresets.grayMagnetize,
    608: abyssPresets.blueFreeze,
    615: abyssPresets.cyanDestroyProjectiles,
    616: abyssPresets.orangeBurn,
    617: abyssPresets.grayMagnetize,
    618: abyssPresets.pinkCharm,
    622: abyssPresets.pinkMimic,
    625: "大型红色蝗虫, 攻击更快",
    629: abyssPresets.cyanDestroyProjectiles,
    631: "2只小型红色蝗虫",
    637: abyssPresets.blueConfuse,
    640: abyssPresets.orangeBurn,
    645: abyssPresets.cyanDestroyProjectiles,
    646: abyssPresets.yellowExplode,
    647: abyssPresets.cyanElectricity,
    652: abyssPresets.blueFreeze,
    663: abyssPresets.cyanDestroyProjectiles,
    683: abyssPresets.grayBones,
    689: abyssPresets.pinkMimic,
    690: abyssPresets.blueConfuse,
    693: "3只青色蝗虫, 阻挡敌人弹幕",
    698: abyssPresets.normalTwo,
    721: abyssPresets.pinkMimic,
    727: abyssPresets.yellowExplode,
    706: "16只不同效果的蝗虫",
}