export const characterAlias = {
    "Isaac":["以撒"],
    "Magdalene":["抹大拉"],
    "Cain":["该隐"],
    "Judas":["犹大"],
    "???":["???","蓝宝","小蓝人","蓝人","？？？"],
    "Eve":["夏娃"],
    "Samson":["参孙"],
    "Azazel":["阿萨泻勒","az","AZ"],
    "Lazarus":["拉撒路"],
    "Eden":["伊甸"],
    "The Lost":["游魂","lost","罗"],
    "Lazarus Risen":["复活的拉撒路"],
    "Dark Judas":["黑暗犹大","犹大之影","黑犹大"],
    "Lilith":["莉莉丝"],
    "Keeper":["店主","店长"],
    "Apollyon":["亚伯伦","亚波伦"],
    "The Forgotten":["遗骸","骨哥"],
    "The Forgotten Soul":["遗骸之魂"],
    "Bethany":["伯大尼"],
    "Jacob and Esau":["雅各和以扫","雅各","以扫","双子"],
    "Tainted Isaac":["堕化以撒","里以撒"],
    "Tainted Magdalene":["堕化抹大拉","里抹","里抹大拉"],
    "Tainted Cain":["堕化该隐","里该隐"],
    "Tainted Judas":["堕化犹大","里犹大"],
    "Tainted ???":["堕化???","里???","里蓝人","里小蓝人"],
    "Tainted Eve":["堕化夏娃","里夏娃"],
    "Tainted Samson":["堕化参孙","里参孙"],
    "Tainted Azazel":["堕化阿萨泻勒","里阿萨泻勒","里az","里AZ"],
    "Tainted Lazarus":["堕化拉撒路","里拉撒路","里拉"],
    "Tainted Eden":["堕化伊甸","里伊甸"],
    "Tainted Lost":["堕化游魂","里游魂","里罗","李罗"],
    "Tainted Lilith":["堕化莉莉丝","里莉莉丝"],
    "Tainted Keeper":["堕化店主","堕化店长","里店主","里店长","里店"],
    "Tainted Apollyon":["堕化亚伯伦","堕化亚波伦","里亚伯伦","里亚波伦","里亚"],
    "Tainted Forgotten":["堕化遗骸","里遗骸","里骨"],
    "Tainted Bethany":["堕化伯大尼","里伯大尼","里伯"],
    "Tainted Jacob":["堕化雅各","里雅各","里双子","里双"],
    "Dead Tainted Lazarus":["死去的堕化拉撒路","死拉"],
    "Tainted Jacob's Soul":["堕化雅各之魂"],
    "Tainted Forgotten Soul":["堕化遗骸之魂"]
}

export const birthrights = {
    "Isaac":"所有道具在2个选择间切换",
    "Magdalene":"↑ {{Heart}} +1心之容器#心上限提高到18",
    "Cain":"↑ {{Luck}} 幸运+1#{{ArcadeRoom}} 后续所有层都含有一个升级的游戏厅(暗室, 玩具箱除外)#{{Collectible46}} 极大增强幸运脚的获胜几率提高的效果",
    "Judas":"{{Collectible34}} 彼列之书变成类似于{{Collectible584}}美德之书的被动道具#{{Collectible34}} 若当前未持有则获得彼列之书#↑ {{Damage}} 获得的伤害加成与在其上的主动道具充能量成比例#某些主动道具会获得特殊效果",
    "???":"{{SoulHeart}} 体力上升获得的魂心翻倍",
    "Eve":"{{Collectible122}} 巴比伦大淫妇和死鸟始终激活",
    "Samson":"{{Collectible157}} 嗜血每层可额外再触发4次, 触发10次至最大+14伤害",
    "Azazel":"阿撒泻勒的硫磺火变得更宽#伤害不提升",
    "Lazarus":"↑ 复活的拉撒路{{Damage}}伤害+7.2#{{Timer}} 获得的伤害在60秒内衰减#{{Blank}} 效果尚存时击杀敌人会延长时间",
    "Eden":"从随机道具池生成3个随机道具#只能拿1个",
    "The Lost":"阻止对游魂无好处的道具生成#比如: 回血, 飞行, 灵体泪弹, 受伤触发的道具",
    "Lazarus Risen":"↑ {{Damage}} 伤害+7.2#{{Timer}} 获得的伤害在60秒内衰减#{{Blank}} 效果尚存时击杀敌人会延长时间",
    "Dark Judas":"{{Collectible34}} 彼列之书变成类似于{{Collectible584}}美德之书的被动道具#{{Collectible34}} 若当前未持有则获得彼列之书#↑ {{Damage}} 获得的伤害加成与在其上的主动道具充能量成比例#某些主动道具会获得特殊效果",
    "Lilith":"跟班在莉莉丝面前位置",
    "Keeper":"↑ {{CoinHeart}} +1硬币心容器#硬币心容器上限为4",
    "Apollyon":"{{Collectible477}} 使用虚空时有几率生成之前被虚空吸收的道具#属性加成仍保留#吸收的道具越多, 生成道具的几率越高",
    "The Forgotten":"遗骸之魂不再绑定, 可自由移动",
    "The Forgotten Soul":"遗骸之魂不再绑定, 可自由移动",
    "Bethany":"{{Battery}} 使用魂心充能激活道具时, 50%几率不消耗魂心充能",
    "Jacob and Esau":"拿起这个道具的角色获得另个角色3个被动道具的复制品",
    "Tainted Isaac":"增加4个额外被动道具槽位#长子名分本身不占用槽位",
    "Tainted Magdalene":"{{Heart}} 不流失的心之容器增加1个#{{HealingRed}} 治疗1红心",
    "Tainted Cain":"道具分解生成的掉落物数量翻倍",
    "Tainted Judas":"{{Collectible705}} 暗仪刺刀击中敌人和弹幕的范围变大",
    "Tainted ???":"{{PoopPickup}} 增加大便最大携带量为29",
    "Tainted Eve":"{{HalfHeart}} 死亡的红心血团生成2秒后消失的半红心",
    "Tainted Samson":"{{Collectible704}} 击杀敌人时狂暴计时增加3秒而不是1秒",
    "Tainted Azazel":"{{Collectible726}} 咯血症攻击大小翻倍",
    "Tainted Lazarus":"未激活的形态作为虚角色#虚角色无敌, 造成0.25x伤害#两个角色都有长子名分的效果",
    "Tainted Eden":"在长子名分之前拿到的道具不会被重置#主动道具放下又拾起后可再次被重置",
    "Tainted Lost":"获得1额外生命#死亡时, 在相同房间中重生并对附近敌人造成200点伤害",
    "Tainted Lilith":"{{Collectible728}} 正常跟随的跟班改为与格罗行为一致#每有1个跟班, 造成的近战伤害+3",
    "Tainted Keeper":"{{Coin}} 强力吸引击杀敌人掉落的硬币#对其他硬币无效果",
    "Tainted Apollyon":"按住发射键使蝗虫持续对敌人造成伤害而不返回",
    "Tainted Forgotten":"{{Collectible714}} 堕化遗骸之魂获得召回能力, 从任意距离召回堕化遗骸#遗骸之魂在遗骸返回时无敌",
    "Tainted Bethany":"生成4个品质{{Quality3}}3和{{Quality4}}4的随机道具魂火, 血量比正常魂火高很多",
    "Tainted Jacob":"堕化以扫分裂为两个#两者会同时冲刺#{{Collectible722}} 孤魂铁索的冷却降至10秒#使用孤魂铁索禁锢两者6.67秒",
    "Dead Tainted Lazarus":"未激活的形态作为虚角色#虚角色无敌, 造成0.25x伤害#两个角色都有长子名分的效果",
    "Tainted Jacob's Soul":"堕化以扫分裂为两个#两者会同时冲刺#{{Collectible722}} 孤魂铁索的冷却降至10秒#使用孤魂铁索禁锢两者6.67秒",
    "Tainted Forgotten Soul":"{{Collectible714}} 堕化遗骸之魂获得召回能力, 从任意距离召回堕化遗骸#遗骸之魂在遗骸返回时无敌"
}

export function GetCharacterByAlias(alias: string): string {
    for (const key in characterAlias) {
        if (characterAlias[key].includes(alias)) {
            return key
        }
    }
    return ""
}